---
title: "hw5_CA_MCA"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(tidyverse)
library(ca)
```

### 5.1 
chairs <- read.csv('https://raw.githubusercontent.com/agricolamz/2019_data_analysis_for_linguists/master/data/students/AnastasiaOrlenko/hw5_CA_MCA/hw5_chairs.csv')

MCA <- MASS::mca(chairs[-c(1:3)])
chairs <- cbind(chairs, MCA$rs)
variables <- as_data_frame(MCA$cs)
variables$var_names <- rownames(MCA$cs)
chairs %>% 
  ggplot(aes(`1`, `2`)) +
  geom_point(aes(color = Category))+
  stat_ellipse(aes(color = Category))+
  geom_text(data = variables, aes(`1`, `2`, label = var_names))+
  theme_bw() +
  scale_x_continuous(limits = c(-0.015, 0.02))


### 5.2
про Stuhl скорее: Function:Outdoor, SaveSpace:collapse, Recline:No, AddFunctions:Table, ... 
про Stessel скорее: Arms:Yes, MaterialSeat:Fabric, Upholst:Yes, Soft:Yes, Back:High, MaterialSeat:Leather, ...
то есть стул (Stuhl) (в отл. от кресла (Stessel)): складной, чаще используется на улице, не раскладывается (как, например, кресла, типа как кресло-кровать); а кресло (Sessel) чаще бывает: с подлокотниками, из ткани, с обивкой, мягкое, с высокой спинкой с кожаным сиденьем. 


### 5.3 
colreg <- read.csv('https://raw.githubusercontent.com/agricolamz/2019_data_analysis_for_linguists/master/data/students/AnastasiaOrlenko/hw5_CA_MCA/hw5_colreg.csv')
rownames(colreg) <- colreg$colors
ca <- ca(colreg[-5])

colreg_col <- data.frame(ca$colcoord)
colreg_col$rows <- rownames(ca$colcoord)
colreg_row <- data.frame(ca$rowcoord)
colreg_row$rows <- rownames(ca$rowcoord)

colreg_col %>% 
  ggplot(aes(Dim1, Dim2, label = rows))+
  geom_text(color = "blue")+
  geom_text(data = colreg_row, color = "red")+
  theme_bw()+
  scale_x_continuous(limits = c(-2.5, 2.5))


### 5.4 
в академическом стиле нет особого разнообразия цветов — чем небазовей цвет —— тем реже он встречается (типа orange, pink, purple), зато более базовые цвета типа black и white встречаются чаще; 
больше всего цветов в подкорпусах press и fiction, притом цвета разнообразные и 
частота употребления цветов связана с их базовостью, так, самысм частоупотребляемыми цветами являются чёрный и белый, потом идут красный, голубой и зелёный. 

